service: serverless-url-shortener

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TABLE_NAME: serverless-url-shortener-table
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: 
            - Fn::GetAtt: [UrlShortenerTable, Arn]

functions:
  shorten:
    handler: handler.shorten
    events:
      - http:
          path: shorten
          method: post
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /{shortCode}
          method: get
  docs:
    handler: swagger.handler
    events:
      - http:
          path: docs
          method: get

resources:
  Resources:
    UrlShortenerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-url-shortener-table
        AttributeDefinitions:
          - AttributeName: shortCode
            AttributeType: S
        KeySchema:
          - AttributeName: shortCode
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST