service: serverless-url-shortener

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  # Đảm bảo không có dấu ngoặc dư thừa ở đây

functions:
  shorten: # Thụt lề 2 dấu cách
    handler: handler.shorten # Thụt lề 4 dấu cách
    events:
      - http:
          path: shorten
          method: post
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /{shortCode}
          method: get
  docs:
    handler: swagger.handler
    events:
      - http:
          path: docs
          method: get